### ISSUE TITLE
Mocking Outbound Emails

### ISSUE THREAD

**Issue by will-holley** [ActiveCampaign/postmark.js#105]
I originally set up my unit tests to run against a Postmark sandbox server and surprisingly discovered that sending emails detracts from my quota. As such, I decided to mock `ServerClient.sendEmail` success.  

I couldn't find a recommended mocking strategy from the Postmark developers so I'm posting my solution here.  Hopefully it will help someone else.

```typescript
import { ServerClient } from "postmark";
import MockAdapter from "axios-mock-adapter";
import { randomUUID } from "crypto";

const pm = new ServerClient(process.env.POSTMARK_API_KEY as string);

if (process.env.MOCK_POSTMARK){
  const mock = new MockAdapter(pm.httpClient.client);

  mock.onPost("/email").reply((config) => {
      const requestBody = JSON.parse(config.data);
      return [
        200,
        {
          ErrorCode: 0,
          Message: "OK",
          MessageID: randomUUID(),
          SubmittedAt: new Date().toISOString(),
          To: requestBody.To
        }
      ];
    });
}
```

**Comment by ibalosh** [comment]
Hi @will-holley 

thank you for letting us know! Would you mind if we use the example in our [wiki](https://github.com/wildbit/postmark.js/wiki)? We might add it there.

Igor
