### ISSUE TITLE
Missing "messagestream" in StatisticsFilteringParameters class

### ISSUE THREAD

**Issue by renyuanz** [ActiveCampaign/postmark.js#113]
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/10615036/186711265-0ef63b62-9c64-4428-a85a-b35720e6b67d.png">

<img width="542" alt="image" src="https://user-images.githubusercontent.com/10615036/186711471-0dd847a7-e5f6-42aa-85d0-b14303dff5d4.png">

As described in the doc, when querying "Stats" there is "messagestream" query string param, but it is missing in the SDK.

Thanks in advance :D

**Comment by renyuanz** [comment]
Hi @ibalosh can you take a look? I'd like to help as well :)

**Comment by ibalosh** [comment]
hi @renyuanz 

thank you for the report. Updated in latest version

Igor
