### ISSUE TITLE
Remove option for http

### ISSUE THREAD

**Issue by camyyssa** [ActiveCampaign/postmark.js#115]
Postmark has announced that starting with November 30 2022 they will no longer support HTTP on their API 👉 https://postmarkapp.com/updates/action-required-postmark-will-no-longer-support-api-request-over-http

😊 This is not a requirement, but it feels like a good idea to also update the official javascript library to no longer offer support for HTTP. Specifically, my guess is that the option `useHttps` from https://github.com/ActiveCampaign/postmark.js/blob/d8508ca0b09b8e2f86de408075ef501e16849a72/src/client/models/client/HttpClient.ts#L23-L25 should be discontinued. 

If you're a developer coming here to do the same investigation for the API behavior change, the setting is already true by default. So if you're not setting it when initializing `ServerClient`, then you should be good. Source: https://github.com/ActiveCampaign/postmark.js/blob/d8508ca0b09b8e2f86de408075ef501e16849a72/src/client/models/client/HttpClient.ts#L9-L13

**Comment by ibalosh** [comment]
Thanks for letting us know @camyyssa 

I will see to do the change this week

**Comment by ibalosh** [comment]
Hi,

actually, we thought about this one a lot. Https is used by default, so no need to hard code it in codebase. We do use extensively the nodejs library for our internal specific testing too, which might include different configurations locally, so we decided to keep this option available.

**Comment by camyyssa** [comment]
👍 No strong opinion on my side, I'm ok with your resolution 😊

Thank you for looking into it!
