### ISSUE TITLE
Inline images issue

### ISSUE THREAD

**Issue by chinnaji** [ActiveCampaign/postmark.js#118]
How do I use base 64 encoded inline images in postmark? Currently, I am using the attachments array and it works but it isn't inline. Please help!!

Even though I'm using the image tag and src as contentId, it shows up like this inline 👇👇, but it shows well in the attached section

![Screenshot_20221223_095722](https://user-images.githubusercontent.com/67190735/209404937-09e4a6e4-64de-4714-bda2-96a7b927a04b.png)

**Comment by ibalosh** [comment]
Hi @chinnaji 

could you send a support ticket to our team, and we will answer the question there? https://postmarkapp.com/contact
Github issues is reserved for bugs.

Before you do, our [wiki](https://github.com/ActiveCampaign/postmark.js/wiki/Email-sending) might help.
Make sure to include a test example you used in support ticket so we can help with resolving the issue quicker.

Thanks
