### ISSUE TITLE
Rotate DKIM keys Does not work

### ISSUE THREAD

**Issue by CheStas** [ActiveCampaign/postmark.js#125]
`accountClient.rotateDomainDKIM` request fails with status code 404
Probably because the wrong request method is used. `POST` should be according to the documentation but  `PUT` is used in the library.

[https://github.com/ActiveCampaign/postmark.js/blob/01af87862ac89d1bfd6d268814a5ff559dad1013/src/client/AccountClient.ts#LL198C1-L198C1](https://github.com/ActiveCampaign/postmark.js/blob/01af87862ac89d1bfd6d268814a5ff559dad1013/src/client/AccountClient.ts#LL198C1-L198C1)

https://postmarkapp.com/developer/api/domains-api#rotate-dkim

**Comment by ibalosh** [comment]
Hi @CheStas 

thank you for reporting this, we will check and fix it
