### ISSUE TITLE
Broken wiki link

### ISSUE THREAD

**Issue by phuze** [ActiveCampaign/postmark.js#127]
There's a broken link on this wiki page:
https://github.com/ActiveCampaign/postmark.js/wiki

**Getting Started** points to https://github.com/ActiveCampaign/postmark-js/wiki/Getting-Started (note the `postmark-js`).
Should be https://github.com/ActiveCampaign/postmark.js/wiki/Getting-Started

**Comment by ibalosh** [comment]
thanks! fixed
