### ISSUE TITLE
Suggestion: Improve Error reporting for .sendEmailWithTemplate

### ISSUE THREAD

**Issue by rdzar** [ActiveCampaign/postmark.js#137]
Thanks for this library, it saves us some work / maintenance on keeping up2date with your REST API. I can't remember the last time I ran into an issue using this library, amazing work keeping it so easy to use & the hassle-free upgrading from v1 -> v2 -> v3. I really love libs that don't force me to rewrite all my code in every major version.

Anyhow.

I, by accident, was inserting the `TemplateAlias` as `TemplateId`, but didn't notice until I started trying random stuff, as the error didn't provide a direction to resolution. I would suggest to improve this situation, so we can all find problems faster and live a happy life.

# Current situation
When you use the function `.sendEmailWithTemplate`, and you provide `TemplateId` with a unknown ID, it will provide you with the following error:
<img width="431" alt="image" src="https://github.com/ActiveCampaign/postmark.js/assets/310687/26712cb9-8dda-41c6-bcdd-051dad794b45">
[``` Received valid, but incompatible JSON input.``` for future reference / search]

# Desired situation
When you use the function `.sendEmailWithTemplate`, and you provide `TemplateId` with a unknown ID, it could reply with something like "Template ID unknown."

# How I'm using this function
I'm directly calling this function, using native promise in Node `v20.5.1`;
```js
 await client.sendEmailWithTemplate({ ... })
 ```

## Lib
```sql
 clientVersion: '3.0.19'
 ```
 
 ## Error Location
 ```sql
 ApiInputError: Received valid, but incompatible JSON input.
    at ApiInputError.buildSpecificError (/postmark/dist/client/errors/Errors.js:124:24)
 ```

**Comment by ibalosh** [comment]
Hi, thank you for reporting this suggestion.

We have forwarded this request to our team which handles Postmark API requests. Since the suggestion is not within the NodeJS library, but within the Postmark API, we will close this ticket.

Igor
