### ISSUE TITLE
DeliveryWebhook: MessageId should be MessageID (ID in all caps)

### ISSUE THREAD

**Issue by boptom** [ActiveCampaign/postmark.js#138]
The `DeliveryWebhook` interface key of `MessageId` should be `MessageID` (where ID is capitalized) to match the POST data of the webhook.

Currently it makes typescript complain with `MessageID does not exist on DeliveyWebhook` when trying to add types the post request.

The interface that needs changing here: https://github.com/ActiveCampaign/postmark.js/blob/main/src/client/models/webhooks/payload/DeliveryWebhook.ts#L7

And the documentation here with the POST data `MessageID`: https://postmarkapp.com/developer/webhooks/delivery-webhook#delivery-webhook-data

Edit: `ServerId` should also be `ServerID` in the same interface.

`DeliveryWebhook.ts` should be:

```
import {Hash} from "../../client/SupportingTypes";

export interface DeliveryWebhook {
    RecordType: string;
    ServerID: number;
    MessageStream: string;
    MessageID: string;
    Recipient: string;
    Tag?: string;
    DeliveredAt: string;
    Details: string;
    Metadata: Hash<string>;
}
```

Thanks!

**Comment by ibalosh** [comment]
thanks for letting us know @boptom! will see to check this out and fix soon

**Comment by ibalosh** [comment]
fix was released
