### ISSUE TITLE
4.0 Migration Documentation

### ISSUE THREAD

**Issue by TKDBB84** [ActiveCampaign/postmark.js#152]
It looks like the [wiki for migration](https://github.com/ActiveCampaign/postmark.js/wiki/Migrating-from-older-version) hasn't been updated to include 4.0.  I assume the only breaking changes were the deprecated versions of node. Can the documentation be update to reflect that, or list any other breaking changes that may have occurred with the new major version? 

Thank you!

**Comment by ibalosh** [comment]
Thanks! No breaking changes in version 4 other than dropping deprecated Node versions. Updated the docs.
