### ISSUE TITLE
Bump Axios to 1.6.8 to address follow-redirects vulnerability

### ISSUE THREAD

**Issue by josh-respectx** [ActiveCampaign/postmark.js#155]
Just wondering if the Axios version is able to be bumped to 1.6.8, which address the potential vulnerability in it's follow-redirects dependency as outlined here: [follow-redirects' Proxy-Authorization header kept across hosts](https://github.com/advisories/GHSA-cxjh-pqwp-8mfp)

Thank you!

**Comment by ibalosh** [comment]
we updated axios version to latest today
