### ISSUE TITLE
Types for JSON webhook data?

### ISSUE THREAD

**Issue by tsongas** [ActiveCampaign/postmark.js#89]
It would be super helpful to have types for JSON webhook data...I don't suppose this exists somewhere and I missed it?

**Comment by ibalosh** [comment]
hu @tsongas 

at the moment we don't have webhook data model within the library.

**Comment by arosemena** [comment]
@ibalosh would you be open to accept a PR for this?

**Comment by ibalosh** [comment]
Hi @arosemena 

yes, we are open for improvements of the library. Once we review the PR we can approve it add it to the codebase.

**Comment by alansikora** [comment]
👍🏻 for this one as well!

**Comment by ibalosh** [comment]
we have released types for web hooks today, it's available as of version 3.0.19.

https://github.com/ActiveCampaign/postmark.js/wiki/Handling-Web-hooks
